# Generated by Django 3.2.6 on 2021-08-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpgavenReeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='reeksfotos/')),
                ('uitleg', models.TextField()),
                ('datum', models.DateField(auto_now_add=True)),
                ('soort', models.CharField(max_length=100)),
                ('onderwerp', models.CharField(max_length=100)),
                ('glob_moeilkhgr', models.CharField(choices=[('*', 'Easy'), ('**', 'Doable'), ('***', 'Hard'), ('****', 'Die hard')], max_length=4)),
                ('glob_strtijd', models.IntegerField()),
                ('vereiste_level', models.CharField(default='Level 4', max_length=50)),
                ('nodig_materiaal', models.CharField(max_length=200)),
                ('joke', models.ImageField(blank=True, null=True, upload_to='reeksfotos/')),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'OpgavenReeks',
                'verbose_name_plural': 'OpgavenReeksen',
            },
        ),
        migrations.CreateModel(
            name='Opgave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onderwerp', models.CharField(max_length=100)),
                ('opg_titel', models.CharField(blank=True, max_length=100)),
                ('opg_foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('opl_foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('opl', models.IntegerField()),
                ('moeilkhgr', models.CharField(choices=[('*', 'Easy'), ('**', 'Doable'), ('***', 'Hard'), ('****', 'Die hard')], max_length=4)),
                ('strtijd', models.IntegerField()),
                ('opgavenreeks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.opgavenreeks')),
            ],
            options={
                'verbose_name': 'Opgave',
                'verbose_name_plural': 'Opgaven',
            },
        ),
    ]
