# Generated by Django 3.2.6 on 2021-08-27 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jouw_antwoord', models.IntegerField(blank=True)),
                ('jouw_delta', models.IntegerField()),
                ('oef_datum', models.DateField(auto_now_add=True)),
                ('juist_fout', models.BooleanField(default=False)),
                ('opgave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.opgave')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oefening',
                'verbose_name_plural': 'Oefeningen',
            },
        ),
    ]
