# Generated by Django 3.2.6 on 2021-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_opgave_type_antw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opgave',
            name='opl',
            field=models.CharField(max_length=100),
        ),
    ]
