# Generated by Django 3.2.6 on 2021-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_alter_opgave_opl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excercice',
            name='jouw_antwoord',
            field=models.CharField(max_length=100),
        ),
    ]
