# Generated by Django 3.2.6 on 2021-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_alter_excercice_jouw_antwoord'),
    ]

    operations = [
        migrations.AddField(
            model_name='excercice',
            name='snelheid',
            field=models.BooleanField(default=False),
        ),
    ]
